print("Welcome to Aegis")
name = input("What's your name? ")
age = input("What's your age? ")
blood = input("What's your blood group? ")
contact = input("Emergency Contact? ")
print("\n----- Patient Information -----")
print("Name:", name)
print("Age:", age)
print("Blood Group:", blood)
print("Emergency Contact:", contact)